apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: inbox-ms
spec:
  hosts:
    - inbox-ms
  http:
  - route:
    - destination:
        host: inbox-ms
        subset: v1
      weight: 50
    - destination:
        host: inbox-ms
        subset: v2
      weight: 50
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: inbox-ms
spec:
  host: inbox-ms
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
